language: node_js
node_js: '5.3'
env:
  global:
  - secure: fvcTDioUhO1lG+16+xdDcbfx5NKkuyEFU3FvfXkAe4N+nUVAgqutT53qr1bI1rMgan6yD7AoVOVa5YjDl6uHRdJAfi1D5kSgHquYwmwZmbafqEVTavM/JnQDOl6bYD38fLfFCYqKkPNUS1ubEDyeFUoJd+2tN3YmQZJyxqsUcOq4kzHavNEQh+cTdD2iQFOEyxJpuHg0eFpDCIU5rGLQndt5ZHROEVkw1qiVokospJpmxd3eK6QP8/Q6BG987g9VkG7qWVBHuvwFR+idy5cX2mVOEkP84uYNfuBfyx6B+rhYCMqINBwa1IBJ8ecW7A6wMOmk2hVYFPaPMgG0DFCU6CNJg738btlBHOrTuMX0uMREwKdZ4N+Y9nlTwlTLk4nv4SYUnT/J2MgRmyv673ilpUekUOf+FNqMwYG7331qxgA2AAkqn5IYr9oeE+YoFvKuF6NwZrT3h1we3J4Um4HPfWaASb0LuiszVkgG+kneakZtAOic4lkvQh+Ox360hH+twpONcCrJdbEOSUn7u+5u4DgVmdS5lSl66EypJ6GHZZfsoiOueIiUQxIAGOmFGNK96biKReSCnLfS9qwZrwfhvy4vNEjeJ5sN2nGHjzOPCee1wL4CazpmP6zpjz+4z/qXrL4u4rs0h7oVu2lhj3ZPxdycd3hTEmvVolmvcFKZrbE=
  - GIT_USER='Jorge Matricali'
  - GIT_EMAIL=jorgematricali@gmail.com
  - GIT_REPO=github.com/matricali/mit-license-8bits-theme.git
before_install:
- git config --global user.name "$GIT_USER"
- git config --global user.email $GIT_EMAIL
- export THEME_VERSION=$(node -e "console.log(require('./package.json').version);")
install: npm install
script: gulp build
after_success: '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ] && gulp deploy || false'
before_deploy: tar -zcvf dist/mit-license-8bits-theme-$THEME_VERSION.tar.gz -C dist themes --transform "s/themes/mit-license-8bits-theme-$THEME_VERSION/"
deploy:
  provider: releases
  api_key:
  skip_cleanup: true
  file_glob: true
    secure: J1VwaakTxfauFQr6EGPtgvllrx1VlA5YX4jwc1qfPh1ZOULdGVoX95hFnpuFQNCtYfAcMHgsgmA1sV19GlXNMSDyMgGwpNZzGvm7ojUVF0GLdWzprHTV0Pbl5xI37zEF92muF2pzk8Xo+tUDARTTioIhM+z9E8nSvUV3PfHcECF2IYMXvIBIu6FNOqTeh+i3SEwoE3lfhiLfi4MkUy/kZzCch918KKP/Ff6nol+5bmOXBqkvbhC/mKZKFpVM/CyvP6wOKhjoWCCUaFCVzvevLglBo8umXwKybd12/MLuA6aQ5taZvglaQVeRYhI8f8PiLGYzS35lYWMEVwHDzYD/xy9CcRahxj/+6c8UQ4k+PZHEq1fdYt9LfMAtmr0upp2IRu7rnKXlufQioAKp8aLOWdOgaYMAWkNIz15NE6GoBPbCniyF/zLEfZ88MUwSmHTmoz7AAFngbqJfnNSCFtGkOixGXVhFIohd5zuAgOn6km/shhrkoBhy+6EGzlzgjLiL+I8H14FXZRsYlu0a45X8PRrPOEVkeufKwqDpVMzkrqWII4mh0oYiZXrAfW9yDYJBdiB1CEy3hV5gXQ82BWsq0FAAWRQXDUPPViq60gh8hECZrKyNYVkADvTZe7sWDkZSDdw+/7xLvCqJxoJ5PEZOQY1XyOAlu19hojMSdza7voA=
  file: dist/mit-license-8bits-theme-*.tar.gz
  on:
    tags: true
    repo: matricali/mit-license-8bits-theme
